name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    name: Mirror repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_MIRROW_TOKEN }}
          GITLAB_USER: ${{ secrets.GITLAB_USERNAME }}
        run: |
          git remote add gitlab "https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/walkcat-mirrow/gateway-service.git"
          git push gitlab "HEAD:${GITHUB_REF_NAME}" --force
